[package]
name = "master"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
axum = { workspace = true }
base64 = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
spider = { path = "../spider" }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net", "rt-multi-thread", "signal"] }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
contrib = { path = "../contrib" }
reqwest = { workspace = true }
