[package]
name = "spider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-openai = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cookie_store = { workspace = true }
encoding_rs = { workspace = true }
erased-serde = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
indexmap = { workspace = true }
kameo = { workspace = true }
mime = { workspace = true }
psl = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
scrape-core = { workspace = true }
selectors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
strsim = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
macros = { path = "../macros" }
